image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

schedule: "0 1 * * *"
imagePullSecret: pull-secret
nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}
