apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pi
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            command: ["./backup.sh"]
            envFrom:
              - configMapRef:
                  name: {{ include "app.name" . }}-secrets
          restartPolicy: Never