name: _deploy

on:
  workflow_call:
    inputs:
      component:
        description: The component to build
        type: string
        required: true
      version:
        description: The version to build
        type: string
        required: true
    secrets:
      cr:
        description: The container registry to use (default is GitHub)
        required: true
      cr_token:
        description: The container registry token
        required: true
      cr_user:
        description: The registry user
        required: true
      kube_config:
        description: The kube config
        required: true

defaults:
  run:
    shell: bash

env:
  COMPONENT: ${{ inputs.component }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      VERSION: ${{ inputs.version }}
      NAMESPACE: pwgen
    steps:
      - uses: actions/checkout@v3
      - name: Kubernetes login
        run: |
          mkdir ~/.kube
          echo "${{ secrets.kube_config }}" > ~/.kube/config
      - name: Kubernetes deploy
        working-directory: chart
        id: helm_deploy
        run: |
          set -ex
          helm dependency update
          helm lint .
          helm package \
            --version "${VERSION}" \
            --app-version "${VERSION}" \
            .
          helm upgrade -i --wait \
            -n ${NAMESPACE} --create-namespace \
            --version ${VERSION} \
            -f values.yaml \
            ${COMPONENT} \
            ${COMPONENT}-${VERSION}.tgz
